### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by giscrazier** [monkeyInShell/react-redux-iapp#6]
npm install 之后npm run start 报错了。
`ERROR in ./node_modules/base16/lib/index.js
Module build failed: ReferenceError: [BABEL] E:\program code\webStorm\react-redux-iapp-master\node_modules\base16\lib\index.js: Using removed Babel 5 option: E:\program code\webStorm\react-redux-iapp-master\node_modules\base16\.babelrc.stage - Check out the corresponding stage-x presets http://babeljs.io/docs/plugins/#presets
`

**Comment by ZhouYK** [comment]
这个问题的确存在，是因为对应的插件没有更新.babelrc配置。
解决办法是：将E:\program code\webStorm\react-redux-iapp-master\node_modules\base16\.babelrc的配置修改为：{"presets": ["env"]}
如果你遇到其他的依赖也出现这个问题，按照这个方法来解决。

**Comment by ZhouYK** [comment]
@giscrazier 项目会持续关注相应的工具更新

**Comment by ZhouYK** [comment]
新改动：在webpack中jsx的loader配置添加了exclude: /node_modules/，解决报错问题了
